/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  smadzudzo
 * Created: Apr 26, 2024
 */

INSERT INTO Address (houseNumber, city, country, line1, line2, postalCode, province, state, street) VALUES
(123, 'Harare', 'Zimbabwe', '123 Main Street', 'Newlands', '12345', 'Harare', NULL, 'Main Street'),
(456, 'Bulawayo', 'Zimbabwe', '456 High Street', 'Hillside', '67890', 'Bulawayo', NULL, 'High Street'),
(789, 'Mutare', 'Zimbabwe', '789 Market Road', NULL, '54321', 'Manicaland', NULL, 'Market Road'),
(101, 'Gweru', 'Zimbabwe', '101 Park Avenue', 'Senga', '98765', 'Midlands', NULL, 'Park Avenue'),
(112, 'Masvingo', 'Zimbabwe', '112 Church Street', 'Rhodene', '45678', 'Masvingo', NULL, 'Church Street'),
(131, 'Kwekwe', 'Zimbabwe', '131 Industrial Road', 'Gaika', '23456', 'Midlands', NULL, 'Industrial Road'),
(151, 'Chitungwiza', 'Zimbabwe', '151 Oxford Street', 'Zengeza', '87654', 'Harare', NULL, 'Oxford Street'),
(171, 'Epworth', 'Zimbabwe', '171 Riverside Drive', 'Sunway City', '76543', 'Harare', NULL, 'Riverside Drive'),
(192, 'Bindura', 'Zimbabwe', '192 Railway Avenue', NULL, '32109', 'Mashonaland Central', NULL, 'Railway Avenue'),
(201, 'Victoria Falls', 'Zimbabwe', '201 Victoria Avenue', 'Mosi-oa-Tunya', '10987', 'Matabeleland North', NULL, 'Victoria Avenue'),
(221, 'Chinhoyi', 'Zimbabwe', '221 Freedom Avenue', 'Chikonohono', '54321', 'Mashonaland West', NULL, 'Freedom Avenue'),
(241, 'Karoi', 'Zimbabwe', '241 Independence Street', 'Chiedza', '98765', 'Mashonaland West', NULL, 'Independence Street'),
(261, 'Chipinge', 'Zimbabwe', '261 Liberty Lane', 'Gaza', '23456', 'Manicaland', NULL, 'Liberty Lane'),
(281, 'Beitbridge', 'Zimbabwe', '281 Unity Road', 'Dulivhadzimu', '87654', 'Matabeleland South', NULL, 'Unity Road'),
(301, 'Chiredzi', 'Zimbabwe', '301 Victory Crescent', 'Chiredzi North', '76543', 'Masvingo', NULL, 'Victory Crescent'),
(321, 'Norton', 'Zimbabwe', '321 Hope Street', 'Makuvaza', '32109', 'Mashonaland West', NULL, 'Hope Street'),
(341, 'Marondera', 'Zimbabwe', '341 Faith Lane', 'Dombotombo', '10987', 'Mashonaland East', NULL, 'Faith Lane'),
(361, 'Ruwa', 'Zimbabwe', '361 Grace Avenue', 'Damafalls', '21098', 'Mashonaland East', NULL, 'Grace Avenue'),
(381, 'Gwanda', 'Zimbabwe', '381 Joy Road', 'Phelandaba', '54321', 'Matabeleland South', NULL, 'Joy Road'),
(401, 'Shurugwi', 'Zimbabwe', '401 Peace Street', 'Zvamahande', '87654', 'Midlands', NULL, 'Peace Street'),
(421, 'Chegutu', 'Zimbabwe', '421 Liberty Lane', 'Chaminuka', '32109', 'Mashonaland West', NULL, 'Liberty Lane'),
(441, 'Gokwe', 'Zimbabwe', '441 Unity Avenue', 'Nembudziya', '10987', 'Midlands', NULL, 'Unity Avenue'),
(461, 'Zvishavane', 'Zimbabwe', '461 Victory Crescent', 'Mabuto', '54321', 'Midlands', NULL, 'Victory Crescent'),
(481, 'Mvuma', 'Zimbabwe', '481 Hope Street', 'Chirumanzi', '87654', 'Midlands', NULL, 'Hope Street'),
(501, 'Banket', 'Zimbabwe', '501 Faith Lane', 'Chakari', '32109', 'Mashonaland West', NULL, 'Faith Lane'),
(521, 'Chitungwiza', 'Zimbabwe', '521 Grace Avenue', 'Zengeza', '10987', 'Harare', NULL, 'Grace Avenue'),
(541, 'Epworth', 'Zimbabwe', '541 Joy Road', 'Sunway City', '54321', 'Harare', NULL, 'Joy Road'),
(561, 'Rusape', 'Zimbabwe', '561 Peace Street', 'Vengere', '87654', 'Manicaland', NULL, 'Peace Street'),
(581, 'Kariba', 'Zimbabwe', '581 Liberty Lane', 'Mahombekombe', '32109', 'Mashonaland West', NULL, 'Liberty Lane'),
(601, 'Murehwa', 'Zimbabwe', '601 Unity Avenue', 'Madziwa', '10987', 'Mashonaland East', NULL, 'Unity Avenue'),
(621, 'Nyanga', 'Zimbabwe', '621 Victory Crescent', 'Dendera', '54321', 'Manicaland', NULL, 'Victory Crescent'),
(641, 'Bindura', 'Zimbabwe', '641 Hope Street', 'Chipadze', '87654', 'Mashonaland Central', NULL, 'Hope Street'),
(661, 'Norton', 'Zimbabwe', '661 Faith Lane', 'Norton Town', '32109', 'Mashonaland West', NULL, 'Faith Lane'),
(681, 'Beitbridge', 'Zimbabwe', '681 Grace Avenue', 'Beitbridge Town', '10987', 'Matabeleland South', NULL, 'Grace Avenue'),
(701, 'Chiredzi', 'Zimbabwe', '701 Joy Road', 'Chiredzi Town', '54321', 'Masvingo', NULL, 'Joy Road'),
(721, 'Karoi', 'Zimbabwe', '721 Peace Street', 'Karoi Town', '87654', 'Mashonaland West', NULL, 'Peace Street'),
(741, 'Gwanda', 'Zimbabwe', '741 Liberty Lane', 'Gwanda Town', '32109', 'Matabeleland South', NULL, 'Liberty Lane'),
(761, 'Chipinge', 'Zimbabwe', '761 Unity Avenue', 'Chipinge Town', '10987', 'Manicaland', NULL, 'Unity Avenue'),
(781, 'Mvuma', 'Zimbabwe', '781 Victory Crescent', 'Mvuma Town', '54321', 'Midlands', NULL, 'Victory Crescent'),
(801, 'Chinhoyi', 'Zimbabwe', '801 Hope Street', 'Chinhoyi Town', '87654', 'Mashonaland West', NULL, 'Hope Street'),
(821, 'Zvishavane', 'Zimbabwe', '821 Faith Lane', 'Zvishavane Town', '32109', 'Midlands', NULL, 'Faith Lane'),
(841, 'Chitungwiza', 'Zimbabwe', '841 Grace Avenue', 'Chitungwiza Town', '10987', 'Harare', NULL, 'Grace Avenue'),
(861, 'Shurugwi', 'Zimbabwe', '861 Peace Street', 'Shurugwi Town', '54321', 'Midlands', NULL, 'Peace Street'),
(881, 'Marondera', 'Zimbabwe', '881 Liberty Lane', 'Marondera Town', '87654', 'Mashonaland East', NULL, 'Liberty Lane'),
(901, 'Ruwa', 'Zimbabwe', '901 Unity Avenue', 'Ruwa Town', '32109', 'Mashonaland East', NULL, 'Unity Avenue'),
(123, 'Harare', 'Zimbabwe', '123 Main Street', 'Central District', '12345', 'Harare', 'Harare', 'Main Street'),
(456, 'Bulawayo', 'Zimbabwe', '456 Second Avenue', 'Western District', '67890', 'Bulawayo', 'Bulawayo', 'Second Avenue'),
(789, 'Mutare', 'Zimbabwe', '789 Third Street', 'Eastern District', '54321', 'Manicaland', 'Manicaland', 'Third Street'),
(101, 'Gweru', 'Zimbabwe', '101 Fourth Road', 'Midlands District', '13579', 'Midlands', 'Midlands', 'Fourth Road'),
(202, 'Masvingo', 'Zimbabwe', '202 Fifth Close', 'Southern District', '97531', 'Masvingo', 'Masvingo', 'Fifth Close'),
(303, 'Kwekwe', 'Zimbabwe', '303 Sixth Lane', 'Central District', '24680', 'Midlands', 'Midlands', 'Sixth Lane'),
(404, 'Chitungwiza', 'Zimbabwe', '404 Seventh Avenue', 'Harare Metropolitan', '08642', 'Harare', 'Harare', 'Seventh Avenue'),
(505, 'Bindura', 'Zimbabwe', '505 Eighth Road', 'Mashonaland Central', '96420', 'Mashonaland Central', 'Mashonaland Central', 'Eighth Road'),
(606, 'Marondera', 'Zimbabwe', '606 Ninth Street', 'Mashonaland East', '02876', 'Mashonaland East', 'Mashonaland East', 'Ninth Street'),
(707, 'Gwanda', 'Zimbabwe', '707 Tenth Close', 'Matabeleland South', '50712', 'Matabeleland South', 'Matabeleland South', 'Tenth Close'),
(808, 'Kadoma', 'Zimbabwe', '808 Eleventh Lane', 'Mashonaland West', '38496', 'Mashonaland West', 'Mashonaland West', 'Eleventh Lane'),
(909, 'Kariba', 'Zimbabwe', '909 Twelfth Avenue', 'Mashonaland West', '03572', 'Mashonaland West', 'Mashonaland West', 'Twelfth Avenue'),
(111, 'Hwange', 'Zimbabwe', '111 Thirteenth Road', 'Matabeleland North', '92035', 'Matabeleland North', 'Matabeleland North', 'Thirteenth Road'),
(222, 'Chipinge', 'Zimbabwe', '222 Fourteenth Street', 'Manicaland', '72504', 'Manicaland', 'Manicaland', 'Fourteenth Street'),
(333, 'Chinhoyi', 'Zimbabwe', '333 Fifteenth Close', 'Mashonaland West', '16928', 'Mashonaland West', 'Mashonaland West', 'Fifteenth Close'),
(444, 'Beitbridge', 'Zimbabwe', '444 Sixteenth Lane', 'Matabeleland South', '40389', 'Matabeleland South', 'Matabeleland South', 'Sixteenth Lane'),
(555, 'Norton', 'Zimbabwe', '555 Seventeenth Avenue', 'Mashonaland West', '70836', 'Mashonaland West', 'Mashonaland West', 'Seventeenth Avenue'),
(666, 'Victoria Falls', 'Zimbabwe', '666 Eighteenth Road', 'Matabeleland North', '92540', 'Matabeleland North', 'Matabeleland North', 'Eighteenth Road'),
(777, 'Ruwa', 'Zimbabwe', '777 Nineteenth Street', 'Mashonaland East', '13870', 'Mashonaland East', 'Mashonaland East', 'Nineteenth Street'),
(888, 'Chegutu', 'Zimbabwe', '888 Twentieth Close', 'Mashonaland West', '24597', 'Mashonaland West', 'Mashonaland West', 'Twentieth Close'),
(999, 'Rusape', 'Zimbabwe', '999 Twenty-First Lane', 'Manicaland', '83245', 'Manicaland', 'Manicaland', 'Twenty-First Lane'),
(121, 'Zvishavane', 'Zimbabwe', '121 Twenty-Second Avenue', 'Midlands', '67024', 'Midlands', 'Midlands', 'Twenty-Second Avenue'),
(232, 'Murehwa', 'Zimbabwe', '232 Twenty-Third Road', 'Mashonaland East', '92647', 'Mashonaland East', 'Mashonaland East', 'Twenty-Third Road'),
(343, 'Epworth', 'Zimbabwe', '343 Twenty-Fourth Street', 'Harare Metropolitan', '34791', 'Harare', 'Harare', 'Twenty-Fourth Street'),
(454, 'Chiredzi', 'Zimbabwe', '454 Twenty-Fifth Close', 'Masvingo', '51063', 'Masvingo', 'Masvingo', 'Twenty-Fifth Close'),
(565, 'Shurugwi', 'Zimbabwe', '565 Twenty-Sixth Lane', 'Midlands', '02548', 'Midlands', 'Midlands', 'Twenty-Sixth Lane'),
(676, 'Gokwe', 'Zimbabwe', '676 Twenty-Seventh Avenue', 'Midlands', '68394', 'Midlands', 'Midlands', 'Twenty-Seventh Avenue'),
(787, 'Kwekwe', 'Zimbabwe', '787 Twenty-Eighth Road', 'Midlands', '47291', 'Midlands', 'Midlands', 'Twenty-Eighth Road'),
(898, 'Karoi', 'Zimbabwe', '898 Twenty-Ninth Street', 'Mashonaland West', '62540', 'Mashonaland West', 'Mashonaland West', 'Twenty-Ninth Street'),
(909, 'Zhombe', 'Zimbabwe', '909 Thirtieth Close', 'Midlands', '87394', 'Midlands', 'Midlands', 'Thirtieth Close'),
(110, 'Mvurwi', 'Zimbabwe', '110 Thirty-First Lane', 'Mashonaland Central', '40296', 'Mashonaland Central', 'Mashonaland Central', 'Thirty-First Lane'),
(221, 'Nkayi', 'Zimbabwe', '221 Thirty-Second Avenue', 'Matabeleland North', '69382', 'Matabeleland North', 'Matabeleland North', 'Thirty-Second Avenue'),
(332, 'Mvuma', 'Zimbabwe', '332 Thirty-Third Road', 'Midlands', '52049', 'Midlands', 'Midlands', 'Thirty-Third Road'),
(443, 'Gutu', 'Zimbabwe', '443 Thirty-Fourth Street', 'Masvingo', '83519', 'Masvingo', 'Masvingo', 'Thirty-Fourth Street'),
(554, 'Raffingora', 'Zimbabwe', '554 Thirty-Fifth Close', 'Mashonaland West', '63058', 'Mashonaland West', 'Mashonaland West', 'Thirty-Fifth Close'),
(665, 'Chivhu', 'Zimbabwe', '665 Thirty-Sixth Lane', 'Mashonaland East', '19475', 'Mashonaland East', 'Mashonaland East', 'Thirty-Sixth Lane'),
(776, 'Centenary', 'Zimbabwe', '776 Thirty-Seventh Avenue', 'Mashonaland Central', '83946', 'Mashonaland Central', 'Mashonaland Central', 'Thirty-Seventh Avenue'),
(887, 'Plumtree', 'Zimbabwe', '887 Thirty-Eighth Road', 'Matabeleland South', '57294', 'Matabeleland South', 'Matabeleland South', 'Thirty-Eighth Road'),
(998, 'Headlands', 'Zimbabwe', '998 Thirty-Ninth Street', 'Manicaland', '30495', 'Manicaland', 'Manicaland', 'Thirty-Ninth Street'),
(123, 'Shamva', 'Zimbabwe', '123 Fortieth Close', 'Mashonaland Central', '93856', 'Mashonaland Central', 'Mashonaland Central', 'Fortieth Close'),
(234, 'Chimanimani', 'Zimbabwe', '234 Forty-First Lane', 'Manicaland', '50297', 'Manicaland', 'Manicaland', 'Forty-First Lane'),
(345, 'Concession', 'Zimbabwe', '345 Forty-Second Avenue', 'Mashonaland Central', '72094', 'Mashonaland Central', 'Mashonaland Central', 'Forty-Second Avenue'),
(456, 'Nyanga', 'Zimbabwe', '456 Forty-Third Road', 'Manicaland', '39047', 'Manicaland', 'Manicaland', 'Forty-Third Road'),
(567, 'Guruve', 'Zimbabwe', '567 Forty-Fourth Street', 'Mashonaland Central', '64023', 'Mashonaland Central', 'Mashonaland Central', 'Forty-Fourth Street'),
(678, 'Chirumanzu', 'Zimbabwe', '678 Forty-Fifth Close', 'Midlands', '85039', 'Midlands', 'Midlands', 'Forty-Fifth Close'),
(789, 'Rushinga', 'Zimbabwe', '789 Forty-Sixth Lane', 'Mashonaland Central', '32058', 'Mashonaland Central', 'Mashonaland Central', 'Forty-Sixth Lane'),
(890, 'Mazowe', 'Zimbabwe', '890 Forty-Seventh Avenue', 'Mashonaland Central', '97340', 'Mashonaland Central', 'Mashonaland Central', 'Forty-Seventh Avenue'),
(901, 'Uzumba-Maramba-Pfungwe', 'Zimbabwe', '901 Forty-Eighth Road', 'Mashonaland East', '64072', 'Mashonaland East', 'Mashonaland East', 'Forty-Eighth Road'),
(112, 'Norton', 'Zimbabwe', '112 Forty-Ninth Street', 'Mashonaland West', '30894', 'Mashonaland West', 'Mashonaland West', 'Forty-Ninth Street'),
(223, 'Binga', 'Zimbabwe', '223 Fiftieth Close', 'Matabeleland North', '54023', 'Matabeleland North', 'Matabeleland North', 'Fiftieth Close'),
(334, 'Buhera', 'Zimbabwe', '334 Fiftieth Lane', 'Manicaland', '67382', 'Manicaland', 'Manicaland', 'Fiftieth Lane'),
(445, 'Goromonzi', 'Zimbabwe', '445 Fiftieth Avenue', 'Mashonaland East', '98235', 'Mashonaland East', 'Mashonaland East', 'Fiftieth Avenue'),
(556, 'Gwanda', 'Zimbabwe', '556 Fiftieth Road', 'Matabeleland South', '50382', 'Matabeleland South', 'Matabeleland South', 'Fiftieth Road'),
(667, 'Gweru', 'Zimbabwe', '667 Fifty-First Street', 'Midlands', '82064', 'Midlands', 'Midlands', 'Fifty-First Street'),
(778, 'Hurungwe', 'Zimbabwe', '778 Fifty-Second Close', 'Mashonaland West', '54028', 'Mashonaland West', 'Mashonaland West', 'Fifty-Second Close'),
(889, 'Hwange', 'Zimbabwe', '889 Fifty-Third Lane', 'Matabeleland North', '82093', 'Matabeleland North', 'Matabeleland North', 'Fifty-Third Lane'),
(900, 'Kariba', 'Zimbabwe', '900 Fifty-Fourth Avenue', 'Mashonaland West', '64093', 'Mashonaland West', 'Mashonaland West', 'Fifty-Fourth Avenue');

INSERT INTO productstatus( id, description, name ) VALUES ( 1, 'Product is free', 'FREE');
INSERT INTO productstatus( id, description, name ) VALUES ( 2, 'Product has been put in a cart', 'CARTED');
INSERT INTO productstatus( id, description, name ) VALUES ( 3, 'Product has been ordered by someone', 'ORDERED');
INSERT INTO productstatus( id, description, name ) VALUES ( 4, 'Product has been purchased', 'PURCHASED');

INSERT INTO producttype( id, description, name ) VALUES ( 1, 'REFRIDGERATOR', 'REFRIDGERATOR');
INSERT INTO producttype( id, description, name ) VALUES ( 2, 'TELEVISION', 'TELEVISION');
INSERT INTO producttype( id, description, name ) VALUES ( 3, 'LEPTOP', 'LAPTOP');
INSERT INTO producttype( id, description, name ) VALUES ( 4, 'SMARTPHONE', 'SMARTPHONE');
INSERT INTO producttype( id, description, name ) VALUES ( 5, 'PRINTER', 'PRINTER');